name = "YTMusicAPI"
uuid = "3f0233e7-8a26-4e6d-a42a-809929892430"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
HTTP = "1.10.19"
JSON3 = "1.14.3"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
